# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
